import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserInfoProvider } from "@/context/userInfoContext";
import { SessionProvider } from "next-auth/react"
import { Session } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }: Readonly<{ children: React.ReactNode, session:Session|null }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
        <UserInfoProvider>{children}</UserInfoProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
