import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserInfoProvider } from "@/context/userInfoContext";
import { SessionProvider } from "next-auth/react";
import { Session } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Adjusted to optionally include session
type RootLayoutProps = {
  children: React.ReactNode;
  session: never;
};

export default function RootLayout({ children, session }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <UserInfoProvider>{children}</UserInfoProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
